kind = "api"
previewPath = "/"
title = "Simple Chat Application"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Java Chat App"
paths = ["/"]

[services.env]
PORT = "8080"

[services.development]
run = "cd simple-java-chat && javac Main.java && java Main"

[services.production]

[services.production.build]
args = ["sh", "-c", "cd simple-java-chat && javac Main.java"]

[services.production.run]
args = ["sh", "-c", "cd simple-java-chat && exec java Main"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/"